it made
VallemSec/Spectra pull request #57
Opened 2024-12-09 11:42 UTC by FayKn

2024-12-09 11:57 UTC, NekoLuka requested changes

2024-12-09 11:57 UTC, NekoLuka commented on decodyService/import_rules.py
> +parser_folder = sys.argv[1]
if no args are given, you would get a KeyError. Please use the .get() function istead of [] notation, so that you get None instead of an error when no args are given.

2024-12-09 11:59 UTC, NekoLuka commented
Could you also move the code to its own folder in the root of the project with a Docker image? This is so that new rules can be loaded into the database by just running the image.

2024-12-09 12:00 UTC, NekoLuka commented
Could you also consider writing the queries with `insert or update` statements? This prevents errors when a duplicate is inserted.

2024-12-10 09:40 UTC, FayKn commented on decodyService/import_rules.py
> +parser_folder = sys.argv[1]
get didn't work I just did an if len > 0

2024-12-10 11:35 UTC, NekoLuka requested changes

2024-12-11 09:03 UTC, NekoLuka approved these changes

2024-12-11 09:05 UTC, merged