Decody docs and stability improvements
VallemSec/Spectra pull request #58
Opened 2024-12-12 08:26 UTC by NekoLuka

2024-12-12 08:37 UTC, FayKn requested changes
Also how are you planning to put the prompts in the database? I'm not sure what's a good place tbh

2024-12-12 08:37 UTC, FayKn commented on decodyService/endpoints/generate.py
> +    category_findings: defaultdict[str, list[DecodyFindingsOutputFormat]] = defaultdict(list)
What in the shit does this do? YUCK

2024-12-12 08:37 UTC, FayKn commented on decodyService/endpoints/load.py
> +        if safe_eval(
Shouldn't there be an else here if the safe_eval is unsafe?
Maybe handy for error handling

2024-12-12 08:51 UTC, NekoLuka commented
I was thinking to extend the rule loading script to also load some other json file or something which contains the prompts in decody-config

2024-12-12 08:54 UTC, FayKn commented
Sure, but we might need to catch possible missing prompts with a warning and make the api spec so that it can give a blank; if you can do that that's fine

2024-12-12 10:16 UTC, NekoLuka commented
So like a default simple prompt if nothing is found? Or an error to even refuse to start the program?

2024-12-12 10:17 UTC, FayKn commented
Just leave the AI portion null

2025-01-14 14:16 UTC, NekoLuka commented on decodyService/endpoints/generate.py
> +    category_findings: defaultdict[str, list[DecodyFindingsOutputFormat]] = defaultdict(list)
The beauty of python type hinting with a sprinkle of magic to prevent KeyNotFoundErrors

2025-01-15 09:40 UTC, FayKn requested changes

2025-01-15 09:40 UTC, FayKn commented on genericParserService/helpers/__init__.py
> +    pattern = re.compile(r"([\w]+):([\w\d!#$%^&]+)@([\w\d\.-_]+):(\d{1,5})/([\w_-]+)")
wtf does this regex do? It's way past the point where you can just assume the other person gets it.

when you explain it also put a test string near it please

Or in general this function?

2025-01-16 13:54 UTC, NekoLuka commented on genericParserService/main.py
> +SQL_STRING = os.getenv("SQL_STRING")
You're right about that, I'll give it a quick fix.

2025-01-17 08:37 UTC, FayKn approved these changes

2025-01-17 08:37 UTC, merged